version: "3"

networks:
  application:
    external: true

services:
  mysql:
    # container_name: todo-mysql
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - application
  app:
    # container_name: todo-app
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      MYSQL_HOST: todo_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - application
    depends_on:
      - mysql

volumes:
  todo-mysql-data: