version: '3'

networks:
  wkernet:
    driver: overlay

services:
  manager:
    image: agent-script:v0.0.1
    working_dir: /app/NTMA_Anomaly/Script/worker/python
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
      placement:
        constraints:
          - "node.role==worker"
    entrypoint:
      - python3
      - worker-manager.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Infrastructure/docker/conf/nginx/nginx-default.conf:/app/NTMA_Anomaly/Infrastructure/docker/conf/nginx/nginx-default.conf
      - ./Infrastructure/docker/conf/monitoring/prometheus/target/cadvisor.json:/app/NTMA_Anomaly/Infrastructure/docker/conf/monitoring/prometheus/target/cadvisor.json
      - ./Infrastructure/docker/conf/monitoring/prometheus/target/fluentd.json:/app/NTMA_Anomaly/Infrastructure/docker/conf/monitoring/prometheus/target/fluentd.json
      - ./Infrastructure/docker/conf/monitoring/prometheus/target/node-exporter.json:/app/NTMA_Anomaly/Infrastructure/docker/conf/monitoring/prometheus/target/node-exporter.json
    networks:
      - wkernet

  #   slave:
  #     image: agent-script:v0.0.1
  #     working_dir: /app/NTMA_Anomaly/Script/worker/python
  #     deploy:
  #       resources:
  #         limits:
  #           cpus: '0.50'
  #           memory: 500M
  #       placement:
  #         constraints:
  #         - "node.role==worker"
  #       mode: global
  #     entrypoint:
  #       - python3
  #       - worker-slave.py
  #     extra_hosts:
  #       - "host.docker.internal:host-gateway"
  #     volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock
  #     depends_on:
  #       - manager
  #     networks:
  #       - wkernet
  
  # hook:
  #   image: agent-script:v0.0.1
  #   working_dir: /app/NTMA_Anomaly/Script/webhook
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 500M
  #   entrypoint:
  #     - python3
  #     - scaling_hook.py
  #     - ${PARAMs}
  #   extra_hosts:
  #   - "host.docker.internal:host-gateway"
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - manager
  #   networks:
  #     - wkernet
    
