FROM debian:bullseye-slim

RUN apt update && \
    apt install -y git \
    docker.io \
    python3 \
    python3-pip \
    apache2-utils \
    jq

RUN mkdir app && \
    git clone https://github.com/Xeus-Territory/NTMA_Anomaly.git -b main /app/NTMA_Anomaly && \
    pip install -r /app/NTMA_Anomaly/Script/requirements.txt