version: '3'

services:
  redis:
    image: redis:alpine3.17
    container_name: redis
    ports:
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    depends_on:
      - redis

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.127.128
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - redis

  prometheus-kafka-adapter:
    image: telefonica/prometheus-kafka-adapter:1.8.0
    container_name: prometheus-kafka-adapter
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: prometheus-metrics
    depends_on:
      - redis
      - kafka

  prometheus:
    image: prom/prometheus:v2.37.6
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
    container_name: prometheus
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9090
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    depends_on:
      - redis

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
    container_name: cadvisor
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8085/containers/
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
    - 8085:8080
    depends_on:
      - redis

# Add service prometheus-nginxlog-exporter