version: "3"

networks:
  application:
    external: true

services:
  server:
    # container_name: nginx-server
    image: nginx-rebuild:v0.0.1
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
    networks:
      - application
    volumes:
      - ./log/access.log:/var/log/nginx/access_server.log
      - ./log/error.log:/var/log/nginx/error.log
