version: "3"

networks:
  application:
    external: true

services:
  server:
    image: xeusnguyen/nginx-1.23.4:allinone
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      placement:
        constraints:
          - "node.role==manager"
    healthcheck:
      test: "curl http://todo_app:3000"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - application
    volumes:
      - ./log/access.log:/var/log/nginx/access_server.log
      - ./log/error.log:/var/log/nginx/error_server.log
      - ./log/modsec_audit.log:/var/log/nginx/modsec_audit.log
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/ddos.conf:/etc/nginx/waf/ddos.conf
      - ./conf/nginx/anti_ddos_challenge.lua:/etc/nginx/lua/anti_ddos_challenge.lua

  # nginx_exporter:
  #   image: nginx/nginx-prometheus-exporter:0.10.0
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 200M
  #     placement:
  #       constraints:
  #         - "node.role==manager"
  #   command:
  #     - '-nginx.scrape-uri=http://todo_server/nginx_status'
  #   ports:
  #     - 9113:9113
  #   labels:
  #     org.label-schema.group: "monitoring"
  #   networks:
  #     - application    
  #   depends_on:
  #     - server
