groups:
  - name: Todo_app_service
    interval: 5s
    rules:
      - record: service_avg_cpu_usage_percentage
        expr: avg(rate(container_cpu_usage_seconds_total{name=~"todo_app.+"}[5m])) by (container_label_com_docker_swarm_service_name) * 100

      - record: service_avg_memory_usage_percentage
        expr: avg (container_memory_working_set_bytes{name=~"todo_app.+"} / container_spec_memory_limit_bytes{name=~"todo_app.+"}) by (container_label_com_docker_swarm_service_name) * 100

      - record: service_avg_network_receive_bytes
        expr: avg(rate(container_network_receive_bytes_total{name=~"todo_app.+"}[5m])) by (container_label_com_docker_swarm_service_name)

      - record: service_avg_network_transmit_bytes
        expr: avg(rate(container_network_transmit_bytes_total{name=~"todo_app.+"}[5m])) by (container_label_com_docker_swarm_service_name)

      - record: myapp_http_upstream_time_seconds_s200_p50
        expr: avg(myapp_http_upstream_time_seconds{status=~"200", quantile="0.5"} > 0)

      - record: myapp_http_upstream_time_seconds_s200_p90
        expr: avg(myapp_http_upstream_time_seconds{status=~"200", quantile="0.9"} > 0)

      - record: myapp_http_upstream_time_seconds_s200_p99
        expr: avg(myapp_http_upstream_time_seconds{status=~"200", quantile="0.99"} > 0)