# my global config
global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.82.31:9100', '192.168.66.128:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.82.31:8080', '192.168.66.128:8080']
  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.82.31:9113']